FROM node:16

#RUN yarn create vite
#RUN yarn global add @vue/cli
#RUN yarn global add @vue/cli-init

WORKDIR /www

#COPY entrypoint.sh /entrypoint.sh
#ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]

ENV HOST 0.0.0.0
